import bike1 from './photos/bike1.jpg'
import bike2 from './photos/bike2.jpg'
import bike3 from './photos/bike3.jpg'
import bike4 from './photos/bike4.jpg'
import bike5 from './photos/bike5.jpg'
import bike6 from './photos/bike6.jpg'
import bike7 from './photos/bike7.jpg'
import bike8 from './photos/bike8.jpg'
import bike9 from './photos/bike9.jpg'
import bike10 from './photos/bike10.jpg'


Expected JSON format:
{
  "make": "Honda",
  "model": "Rebel",
  "transmission": "Manual",
  "engine": "V-Twin",
  "id": 1,
  "miles": 1000,
  "price": 8000,
  "images": [bike1, bike2, bike3, bike4, bike5, bike6, bike7],
  "color": "Red",
  "vin": "123456789",
  "bodyStyle": "Cruiser",
  "comments": "Great bike for beginners",
  "year": 2022
},


export const testBikes = {
  1: {
    "make": "Honda",
    "model": "Rebel",
    "transmission": "Manual",
    "engine": "V-Twin",
    "id": 1,
    "miles": 1000,
    "price": 8000,
    "images": [bike1, bike2, bike3, bike4, bike5, bike6, bike7],
    "color": "Red",
    "vin": "123456789",
    "bodyStyle": "Cruiser",
    "comments": "Great bike for beginners",
    "year": 2022
  },
  2: {
    "make": "Yamaha",
    "model": "YZF",
    "transmission": "Automatic",
    "engine": "Inline Four",
    "id": 2,
    "miles": 500,
    "price": 12000,
    "images": [bike2, bike2, bike3, bike4, bike5, bike6, bike7],
    "color": "Blue",
    "vin": "987654321",
    "bodyStyle": "Sportbike",
    "comments": "Powerful and stylish",
    "year": 2023
  },  
  3: {
    "make": "Honda",
    "model": "CBR1000RR",
    "transmission": "Manual",
    "engine": "Inline Four",
    "id": 3,
    "miles": 1200,
    "price": 16000,
    "images": [bike3, bike2, bike3, bike4, bike5, bike6, bike7],
    "color": "Blue",
    "vin": "123456789",
    "bodyStyle": "Sportbike",
    "comments": "Powerful and agile",
    "year": 2022
  },
  4: {
    "make": "BMW",
    "model": "R1200GS",
    "transmission": "Manual",
    "engine": "Boxer Twin",
    "id": 4,
    "miles": 400,
    "price": 18000,
    "images": [bike4, bike2, bike3, bike4, bike5, bike6, bike7],
    "color": "Silver",
    "vin": "567812349",
    "bodyStyle": "Adventure",
    "comments": "Versatile and rugged",
    "year": 2023
  },
  5: {
    "make": "Ducati",
    "model": "Panigale V4",
    "transmission": "Automatic",
    "engine": "V4",
    "id": 5,
    "miles": 200,
    "price": 28000,
    "images": [bike5, bike2, bike3, bike4, bike5, bike6, bike7],
    "color": "Red",
    "vin": "765489012",
    "bodyStyle": "Sportbike",
    "comments": "Performance-driven and stylish",
    "year": 2023
  },
  6: {
    "make": "Triumph",
    "model": "Bonneville T120",
    "transmission": "Manual",
    "engine": "Parallel Twin",
    "id": 6,
    "miles": 1500,
    "price": 11000,
    "images": [bike6, bike2, bike3, bike4, bike5, bike6, bike7],
    "color": "Black/White",
    "vin": "345678912",
    "bodyStyle": "Classic",
    "comments": "Retro style with modern tech",
    "year": 2022
  },
  7: {
    "make": "Suzuki",
    "model": "Hayabusa",
    "transmission": "Manual",
    "engine": "Inline Four",
    "id": 7,
    "miles": 700,
    "price": 16000,
    "images": [bike7, bike2, bike3, bike4, bike5, bike6, bike7],
    "color": "Black",
    "vin": "234567891",
    "bodyStyle": "Sport Touring",
    "comments": "High speed and comfort",
    "year": 2023
  },
  8: {
    "make": "KTM",
    "model": "390 Duke",
    "transmission": "Manual",
    "engine": "Single Cylinder",
    "id": 8,
    "miles": 300,
    "price": 5000,
    "images": [bike8, bike2, bike3, bike4, bike5, bike6, bike7],
    "color": "Orange",
    "vin": "876543210",
    "bodyStyle": "Naked Bike",
    "comments": "Agile and fun",
    "year": 2022
  },
  9: {
    "make": "Aprilia",
    "model": "RSV4",
    "transmission": "Manual",
    "engine": "V4",
    "id": 9,
    "miles": 600,
    "price": 23000,
    "images": [bike9, bike2, bike3, bike4, bike5, bike6, bike7],
    "color": "Black/Red",
    "vin": "908765432",
    "bodyStyle": "Sportbike",
    "comments": "Race ready and aggressive",
    "year": 2023
  },
  10: {
    "make": "Moto Guzzi",
    "model": "V7 Stone",
    "transmission": "Manual",
    "engine": "V-Twin",
    "id": 10,
    "miles": 1000,
    "price": 9000,
    "images": [bike10, bike2, bike3, bike4, bike5, bike6, bike7],
    "color": "Gray",
    "vin": "109876543",
    "bodyStyle": "Classic",
    "comments": "Unique character and style",
    "year": 2022
  },
  11: {
    "make": "Royal Enfield",
    "model": "Himalayan",
    "transmission": "Manual",
    "engine": "Single Cylinder",
    "id": 11,
    "miles": 1500,
    "price": 4500,
    "images": [bike1, bike2, bike3, bike4, bike5, bike6, bike7],
    "color": "White",
    "vin": "543210987",
    "bodyStyle": "Adventure",
    "comments": "Reliable and rugged",
    "year": 2022
  },
  12: {
    "make": "Buell",
    "model": "XB12R",
    "transmission": "Manual",
    "engine": "V-Twin",
    "id": 12,
    "miles": 1700,
    "price": 7500,
    "images": [bike1, bike2, bike3, bike4, bike5, bike6, bike7],
    "color": "Red",
    "vin": "654321098",
    "bodyStyle": "Sportbike",
    "comments": "Unique design and performance",
    "year": 2021
  },
  13: {
    "make": "Vespa",
    "model": "GTS 300",
    "transmission": "Automatic",
    "engine": "Single Cylinder",
    "id": 13,
    "miles": 200,
    "price": 6500,
    "images": [bike1, bike2, bike3, bike4, bike5, bike6, bike7],
    "color": "Blue",
    "vin": "765432109",
    "bodyStyle": "Scooter",
    "comments": "Stylish and practical",
    "year": 2023
  },
  14: {
    "make": "Indian",
    "model": "Scout Bobber",
    "transmission": "Manual",
    "engine": "V-Twin",
    "id": 14,
    "miles": 900,
    "price": 15000,
    "images": [bike1, bike2, bike3, bike4, bike5, bike6, bike7],
    "color": "Black",
    "vin": "987654320",
    "bodyStyle": "Cruiser",
    "comments": "Sleek and powerful",
    "year": 2022
  },
  15: {
    "make": "Benelli",
    "model": "TNT 300",
    "transmission": "Manual",
    "engine": "Parallel Twin",
    "id": 15,
    "miles": 600,
    "price": 4500,
    "images": [bike1, bike2, bike3, bike4, bike5, bike6, bike7],
    "color": "White/Red",
    "vin": "098765431",
    "bodyStyle": "Naked Bike",
    "comments": "Sporty and affordable",
    "year": 2021
  },
  16: {
    "make": "MV Agusta",
    "model": "Brutale 1000 RR",
    "transmission": "Manual",
    "engine": "Inline Four",
    "id": 16,
    "miles": 500,
    "price": 33000,
    "images": [bike1, bike2, bike3, bike4, bike5, bike6, bike7],
    "color": "Red/Black",
    "vin": "098765432",
    "bodyStyle": "Naked Bike",
    "comments": "Exquisite design and high performance",
    "year": 2023
  },
  17: {
    "make": "Norton",
    "model": "Commando 961",
    "transmission": "Manual",
    "engine": "Parallel Twin",
    "id": 17,
    "miles": 1000,
    "price": 20000,
    "images": [bike1, bike2, bike3, bike4, bike5, bike6, bike7],
    "color": "Green",
    "vin": "123456789",
    "bodyStyle": "Classic",
    "comments": "Classic British motorcycle",
    "year": 2021
  },
  18: {
    "make": "Bimota",
    "model": "DB7",
    "transmission": "Manual",
    "engine": "V-Twin",
    "id": 18,
    "miles": 700,
    "price": 30000,
    "images": [bike1, bike2, bike3, bike4, bike5, bike6, bike7],
    "color": "Red/White",
    "vin": "876543219",
    "bodyStyle": "Sportbike",
    "comments": "Exclusive and high-performance",
    "year": 2019
  },
  19: {
    "make": "Zero Motorcycles",
    "model": "SR/F",
    "transmission": "Automatic",
    "engine": "Electric",
    "id": 19,
    "miles": 1500,
    "price": 19000,
    "images": [bike1, bike2, bike3, bike4, bike5, bike6, bike7],
    "color": "Blue",
    "vin": "567432109",
    "bodyStyle": "Naked Bike",
    "comments": "Powerful electric performance",
    "year": 2023
  },
  20: {
    "make": "Harley Davidson",
    "model": "Street Glide",
    "transmission": "Manual",
    "engine": "V8",
    "id": 20,
    "miles": 300,
    "price": 17500,
    "images": [bike2, bike2, bike3, bike4, bike5, bike6, bike7],
    "color": "Black",
    "vin": "456789123",
    "bodyStyle": "Cruiser",
    "comments": "Classic cruiser with modern features",
    "year": 2021
  }
};
